### PR TITLE
Some small refactor

### PR DESCRIPTION
**Pull request by Kaffeine**

### CODE REVIEW

**Comment by yavl** [comment]
nice work, though has to be tested with players before merge.

**Comment by Kaffeine** [comment]
(rebased ontop of the current master)

**Comment by yavl** [comment]
@bretonium are these commits in your running server?

**Comment by bretonium** [comment]
no

**Comment by Kaffeine** [comment]
@yavl the commits are not running anywhere yet.
breton is running a quite different version (up to, but not including your https://github.com/yavl/teeworlds-infclassR/commit/433ad0799f511d51ba64a4117ad2e4782006ba92): https://github.com/bretonium/my-infclass-server

**Comment by Kaffeine** [comment]
@yavl
The commits (except GameContext / Count* patches that adjust the refactoring 433ad07) are now running on the breton server. Seems to be harmless.

**Pull request merged**
