### PR TITLE
initial infection rewrite

### LINKED ISSUE #126: Initial infection is out of order
Steps to reproduce:

1. Join a server
2. Wait till more people join
3. Join as spectator and wait for rounds to switch

Expected: initial infected are chosen in order
Observed: after some time, almost always one person gets selected to become initial zombie

This is not reproducible on oi8306. This is reproducible on test oi8306 or any other server based on current `master`.

### PR DESCRIPTION
**Pull request by teoman002**
resolves #126

### CODE REVIEW

**Comment by bretonium** [comment]
Could you please describe how the behavior changed? What changes should i expect with it?

**Comment by teoman002** [comment]
- players do not get infected in two rounds consecutively
- If there are players A, B, C, D: [B, C] get infected, then [A, D], then [B, C]

**Comment by bretonium** [comment]
Why was random added then?

**Comment by teoman002** [comment]
If you have more than 4 players, players will be infected randomly but not consecutively in two rounds
In fact I did not add the random, it was already there.

**Comment by bretonium** [comment]
>  In fact I did not add the random, it was already there.

Actually yes, sorry. But i guess it never worked before

**Comment by teoman002** [comment]
The new behaviour can be tested on the Procrastination Infclass server.

**Comment by teoman002** [comment]
Todo:
- if initial infected > humans , stop initial infection

**Pull request merged**
