### PR TITLE
Add new map infc_headquarter

### PR DESCRIPTION
**Pull request by ResamVi**
Map was from discontinued mod counter-strike: tee time and I modified it to suit infclass gameplay
infc_headquarter

### CODE REVIEW

**Comment by bretonium** [comment]
The map looks good. However what bothers me is lack of license for it. https://github.com/Siile/CSTT doesn't feature a repo-wide license and map's "License" field is empty.

@ResamVi, do you have a license from the map author to use it? If no, we could get in contact with them to get it

**Comment by ResamVi** [comment]
FFTUPDM license (feel free to use private discord message license)
i asked him last saturday
Imgur

**Comment by Kaffeine** [comment]
Hi upstream, I would appreciate you to give some answer. The author of the original map said "ofc, feel free to (use it)"

**Comment by bretonium** [comment]
I emailed the author of the map and asked to license the map under more formal license, but got no response. Since we already had problems with people being not happy that we use their map without explicit consent from their side, i'd say we should not merge it until we get a proper license.

**Comment by teoman002** [comment]
@ResamVi checked the license, will be used until the author withdraws his approval.

**Pull request merged**
