### PR TITLE
removed comments

### PR DESCRIPTION
**Pull request by duralakun**
/* INFECTION MODIFICATION START ***************************************/
and
/* INFECTION MODIFICATION END ***************************************/
are often not true and can be misleading. Waste space and dont look good.

There are no comments in the code thanking any persons, except for one, i dont think this is necessary.
There is a contributor list for thanking people.

### CODE REVIEW

**Comment by yavl** [comment]
If someone would like to port/rewrite infclass for a 0.7+ tw, these comments may provide a little bit of help won't they? Anyway for now they don't seem to hurt that much to be removed

**Comment by bretonium** [comment]
Removing these comments directly violates teeworlds license

**Comment by duralakun** [comment]
@bretonium are you referring to this:

> 2. Altered source versions must be plainly marked as such, and must not be
> misrepresented as being the original software.

I think this means that we should not claim that this is repo is the original / unmodified code of teeworlds. It is obvious that this is a modifcation of tw. DDNet the biggest mod of tw also has no comments around every change in the source code.

**Comment by bretonium** [comment]
> @bretonium are you referring to this:
> 
> > 1. Altered source versions must be plainly marked as such, and must not be
> >    misrepresented as being the original software.
> 
> I think this means that we should not claim that this repo is the original / unmodified code of teeworlds. It is obvious that this is a modifcation of tw. DDNet the biggest mod of tw also has no comments around every change in the source code.

I concur. I always thought that these comments are there to comply with the license, but after googling it seems that we were supposed to just (c) the changed files in their headers: https://softwareengineering.stackexchange.com/questions/220068/file-with-apache-2-0-and-my-modifications (apache2 has a similar cause in it).

**Pull request closed without merging**
