### PR TITLE
reduce max scientist mines to 1 if not enough players are online

### PR DESCRIPTION
**Pull request by duralakun**
Only allow one scientist mine per scientist until there are atleast 3 players on.
1 v 1 a scientist can block himself with 2 mines and make it impossible to kill him.
#48

### CODE REVIEW

**Comment by teoman002** [comment]
Thanks for your fix @duralakun . I will integrate this in my new PR for #48

**Comment by bretonium** [comment]
wtf, we could just merge it for tomorrow game and now wait for another pr

**Comment by teoman002** [comment]
has to be reverted, after pulling the new PR from me.

**Comment by teoman002** [comment]
This is obsolete.

**Pull request closed without merging**
